[solute_layer]
order = 1.0
label = "Layer containing the solute"
type = "integer"
default = 1
minimum = 1
maximum = 100

[solvent_layer]
order = 2.0
label = "Layer containing a solvent molecule"
type = "integer"
default = 2
minimum = 1
maximum = 100

[nsolv]
order = 3.0
label = "Number of solvent molecules to add"
type = "integer"
default = 4
minimum = 1
maximum = 1000

[warning]
order = 4.0
label = "WARNING"
type = "text"
default = "QCG calculations with versions 3.0.x of CREST have a bug, so this command is currently unlikely to work!"
